name: Drools LSP

on:
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'docsimg/**'
      - '.ci/jenkins/**'

jobs:
  drools-build:
    concurrency:
      group: drools-lsp-${{ matrix.os }}_pr-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 120
    strategy:
      matrix:
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]
        java-version: [11]
        maven-version: ['3.8.6']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    steps:
      - name: Clean Disk Space
        uses: kiegroup/kogito-pipelines/.ci/actions/ubuntu-disk-space@main
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: kiegroup/kogito-pipelines/.ci/actions/long-paths@main
      - name: Java and Maven Setup
        uses: kiegroup/kogito-pipelines/.ci/actions/maven@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn -B clean install

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Check Java version
        run: java -version

      - name: Set Java Home
        env:
          JAVA_HOME: $(readlink -f $(which java))/../..
        if: runner.os == 'macOS'

      - name: Echo JAVA_HOME
        run: echo "JAVA_HOME | $JAVA_HOME"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Echo JAVA_HOME
        run: echo "JAVA_HOME | $JAVA_HOME"

      - run: npm install
        working-directory: ./client
      - name: Extension E2E Test for Linux
        run: xvfb-run -a npm test
        working-directory: ./client
        if: runner.os == 'Linux'

      - name: Echo JAVA_HOME
        run: echo "JAVA_HOME | $JAVA_HOME"

      - name: Extension E2E Test
        run: npm test
        working-directory: ./client
        if: runner.os != 'Linux'
